version: 2.1

parameters:
  run-server-tests:
    type: boolean
    default: false
  run-client-tests:
    type: boolean
    default: false

executors:
  node-exec:
    docker:
      - image: cimg/node:lts
    working_directory: ~/app

jobs:
  test-server:
    executor: node-exec
    steps:
      - checkout
      - run: cd server && npm ci
      - run: npm test

  build-client:
    executor: node-exec
    steps:
      - checkout
      - run: cd client && npm ci
      - run: npm run build

  test-client:
    executor: node-exec
    steps:
      - checkout
      - run: cd client && npm ci
      - run: npm test

workflows:
  run-server-tests:
    when: << pipeline.parameters.run-server-tests >>
    jobs:
      - test-server
  build-and-test-client:
    when: << not pipeline.parameters.run-client-tests >>
    jobs:
      - build-client
      - test-client:
          requires:
            - build-client