name: carastore-catalog

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 5050:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql-data:/var/lib/mysql

  nodejs-server:
    build:
      context: .
    restart: on-failure:3
    environment:
      PORT: ${PORT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5000:5000"
    depends_on:
      mysql-db:
        condition: service_healthy
        restart: true

volumes:
  mysql-data:
    name: "mysql-db-data"
